#
#
# things you probably want to change
#
#

# no trailing slash
#url: https://point-theme.netlify.app

# for header and meta tags
title: Isaac Schmidt
description: UC Berkeley MA Class of 2022

# set external to true if linking outside your website
# for internal, make sure to include preceding slash
nav-links:
  - name: Home
    url: /
    external: false
  - name: Work
    url: /work
    external: false
  - name: Projects
    url: /projects
    external: false
  - name: Blog
    url: /blog

# for the homepage image + big text next to it
greeting_image: /assets/isaac.jpg
# 100-200 characters recommended
greeting_text: Hey there! I am currently an Associate Research Analyst at CNA Corporation in Arlington, VA. I hold a Master's degree in Statistics from UC Berkeley, as well as Bachelor's degree in Statistics from Cal, with minors in City Planning and Data Science.
# show blog post excerpts on blog page
show_excerpts: false
excerpt_word_count: 70

# long date: April 20, 1969
long_date: true
# short date: Apr ‘69
short_date: false

#
#
# things you probably don't want to change
#
#
defaults:
  - # applies the default layout to all files in the project
    scope:
      path: ""
    values:
      layout: "default"
  - # sets is_post=true for all blog posts
    scope:
      path: ""
      type: posts
    values:
      is_post: true

collections:
  posts:
    output: true
    permalink: /blog/:title

permalink: /:title # so we have /about instead of /about.html, and /blog-post instead of /2019-11-22-blog-post.html
sass:
  style: compressed # compress the CSS file generated from the SCSS styles file
